sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t moussavdb/trinitycore:latest -t moussavdb/trinitycore:build_$TRAVIS_BUILD_NUMBER .
script:
  - docker images moussavdb/trinitycore
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/trinitycore:latest;
    docker push moussavdb/trinitycore:build_$TRAVIS_BUILD_NUMBER;
